# Puerto donde corre este microservicio
server.port=8082

# Nombre del servicio
spring.application.name=orbitrack-orders

# Base de datos en memoria H2 — solo para desarrollo
spring.datasource.url=jdbc:h2:mem:pedidosdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=orbitrack
spring.datasource.password=orbitrack2024

# Configuracion JPA — crea tablas automaticamente al iniciar
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

# Consola visual H2 — ver datos en el navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console