# Puerto donde corre el BFF
server.port=8080

# Nombre del servicio
spring.application.name=orbitrack-gateway

# URL base de los microservicios
orbitrack.inventario.url=http://localhost:8081
orbitrack.pedidos.url=http://localhost:8082